name: dart_spell
version: 0.1.1
description: Simple spell checker for Dart
homepage: https://github.com/ahmetaa/dart-spell
environment:
  sdk: '>=2.7.0 <3.0.0'
dev_dependencies:
  unittest: '>=0.9.0 <0.10.0'
