name: spell_checker
version: 0.1.2+1

description: Simple spell checker for Dart
homepage: https://github.com/almaclaine/dart-spell

environment:
  sdk: '>=2.7.0 <3.0.0'

dev_dependencies:
  test: ^1.14.2
  effective_dart: ^1.2.1
  list_english_words: ^0.1.1